p, d= map(float, input('hey!, pls gimme 1- p num 2- diameter separated with single space:').split())
r = float(d/2)
cp = float(d*p)
ca = float(r*r*p)
print('perimeter of circle: %.3f and area of circle: %.3f' %(cp, ca) )